import { supabase } from "@/lib/supabase";
export type VerificationStatus="Verified"|"Pending"|"Rejected"; export type SubscriptionTier="Pro"|"Free"; export type UserRole="user"|"professional"|"admin";
export type AdminUser={id:string;name:string;profession:string;email:string;phone:string;location:string;verified:boolean;verificationStatus:VerificationStatus;subscription:SubscriptionTier;role:UserRole;isSuspended:boolean;avatar:any;memberSince:string;lastActive:string};
let cache:AdminUser[]=[];
function mapUser(row:any,pro?:any,sub?:any):AdminUser{return{id:row.id,name:row.full_name??"Unnamed User",profession:pro?.profession??"User",email:row.email??"",phone:row.phone??"",location:row.city??pro?.city??"",verified:Boolean(pro?.is_verified),verificationStatus:pro?.is_verified?"Verified":"Pending",subscription:sub?.status==="active"&&sub?.plan_code==="pro"?"Pro":"Free",role:(row.role??"user") as UserRole,isSuspended:Boolean(row.is_suspended),avatar:row.avatar_url?{uri:row.avatar_url}:undefined,memberSince:row.member_since??row.created_at??"",lastActive:row.last_active_label??row.last_active_at??""};}
export async function listUsersAsync():Promise<AdminUser[]>{const [profiles,pros,subs]=await Promise.all([supabase.from("profiles").select("id,full_name,phone,email,avatar_url,role,city,is_suspended,member_since,created_at,last_active_label,last_active_at").order("created_at",{ascending:false}),supabase.from("professionals").select("id,user_id,profession,city,is_verified"),supabase.from("professional_subscriptions").select("id,user_id,professional_id,plan_id,plan_code,status")]);const err=[profiles,pros,subs].find(r=>r.error)?.error;if(err)throw err;const pm=new Map((pros.data??[]).map((p:any)=>[p.user_id,p]));const sm=new Map((subs.data??[]).filter((s:any)=>s.status==="active").map((s:any)=>[s.user_id,s]));cache=(profiles.data??[]).map((p:any)=>mapUser(p,pm.get(p.id),sm.get(p.id)));return cache;}
export function listUsers(){return cache;} export async function getUserByIdAsync(id:string){return(await listUsersAsync()).find(u=>u.id===id);}
export async function suspendUser(id:string){const{error}=await supabase.from("profiles").update({is_suspended:true}).eq("id",id);if(error)throw error;return getUserByIdAsync(id);}
export async function unsuspendUser(id:string){const{error}=await supabase.from("profiles").update({is_suspended:false}).eq("id",id);if(error)throw error;return getUserByIdAsync(id);}
export async function updateUser(id:string,input:Partial<Pick<AdminUser,"name"|"profession"|"email"|"phone"|"location"|"verificationStatus"|"subscription"|"role">>){const patch:any={};if(input.name!==undefined)patch.full_name=input.name;if(input.email!==undefined)patch.email=input.email;if(input.phone!==undefined)patch.phone=input.phone;if(input.location!==undefined)patch.city=input.location;if(input.role!==undefined)patch.role=input.role;if(Object.keys(patch).length){const{error}=await supabase.from("profiles").update(patch).eq("id",id);if(error)throw error;}const pro=await supabase.from("professionals").select("id").eq("user_id",id).maybeSingle();if(pro.error)throw pro.error;if(pro.data){const pp:any={};if(input.profession!==undefined)pp.profession=input.profession;if(input.verificationStatus!==undefined)pp.is_verified=input.verificationStatus==="Verified";if(Object.keys(pp).length){const{error}=await supabase.from("professionals").update(pp).eq("id",pro.data.id);if(error)throw error;}}return getUserByIdAsync(id);}
